#!/usr/bin/env python3
"""Import legacy asciicker.com prototype PNGs and sliced XP assets.

The xx/yy browser prototypes use PNG-backed sprites directly. The C++ runtime
loads XP assets, so this importer preserves those PNGs as source references and
only creates XP sheets when the prototype declares a rectangular frame layout
that maps cleanly to the C++ sprite atlas contract.
"""

from __future__ import annotations

import argparse
import hashlib
import json
import shutil
import sys
import urllib.error
import urllib.request
from dataclasses import dataclass
from pathlib import Path

from PIL import Image

REPO_ROOT = Path(__file__).resolve().parents[2]
if str(REPO_ROOT) not in sys.path:
    sys.path.insert(0, str(REPO_ROOT))

from scripts.pipeline.xp_core import XPFile, XPLayer


DEFAULT_SOURCE_ROOT = REPO_ROOT / "output"
DEFAULT_IMAGE_OUT = REPO_ROOT / "assets" / "images" / "legacy_asciicker"
DEFAULT_XP_OUT = REPO_ROOT / "assets" / "sprites"
DEFAULT_SLICE_DIRNAME = "slices"
STATIC_BASE_URL = "https://asciicker.com"
TRANSPARENT_KEY = (255, 255, 85)
WHITE = (255, 255, 255)
BLACK = (0, 0, 0)
STATIC_FMT1_KEY_INDEX = 11
STATIC_FMT1_PALETTE = (
    (0, 0, 0), (170, 0, 0), (0, 170, 0), (170, 85, 0),
    (0, 0, 170), (170, 0, 170), (0, 170, 170), (170, 170, 170),
    (85, 85, 85), (255, 85, 85), (85, 255, 85), TRANSPARENT_KEY,
    (85, 85, 255), (255, 85, 255), (85, 255, 255), (255, 255, 255),
)


@dataclass(frozen=True)
class LegacyAsset:
    world: str
    filename: str
    output_name: str
    kind: str
    fmt: int = 0


@dataclass(frozen=True)
class LegacySpriteSpec:
    world: str
    filename: str
    output_name: str
    frame_cols: int
    frame_rows: int
    angles: int
    anim_lengths: tuple[int, ...]
    layout: str
    kind: str


@dataclass(frozen=True)
class LegacySliceSpec:
    world: str
    filename: str
    output_name: str
    frame_cols: int
    frame_rows: int
    kind: str


STATIC_VERSION_FILES = {
    "x3": (("house.png", "prop", 1),),
    "x4": (("house.png", "prop", 1),),
    "x5": (("house.png", "prop", 1), ("map.png", "terrain", 0)),
    "x6": (("house.png", "prop", 1), ("map.png", "terrain", 0)),
    "x7": (("house.png", "prop", 1), ("map.png", "terrain", 0), ("temp.png", "reference", 0)),
    "x8": (("house.png", "prop", 1), ("map.png", "terrain", 0), ("player.png", "reference_actor", 1)),
    "x9": (("house.png", "prop", 1), ("map.png", "terrain", 0), ("player.png", "reference_actor", 1), ("tree.png", "prop", 1), ("shot.xp", "shot_reference", 0)),
    "x10": (("house.png", "prop", 1), ("map.png", "terrain", 0), ("player.png", "reference_actor", 1), ("tree.png", "prop", 1), ("shot.xp", "shot_reference", 0)),
    "x11": (("house.png", "prop", 1), ("map.png", "terrain", 0), ("player.png", "reference_actor", 1), ("tree.png", "prop", 1), ("shot.xp", "shot_reference", 0)),
    "x12": (("house.png", "prop", 1), ("map.png", "terrain", 0), ("player.png", "reference_actor", 1), ("tree.png", "prop", 1), ("sky.png", "backdrop", 1), ("shot.xp", "shot_reference", 0)),
    "x13": (("house.png", "prop", 1), ("map2.png", "terrain", 0), ("player.png", "reference_actor", 1), ("tree.png", "prop", 1), ("sky.png", "backdrop", 1), ("shot.xp", "shot_reference", 0)),
    "xx": (("house.png", "prop", 1), ("map.png", "terrain", 0), ("player.png", "reference_actor", 1), ("tree.png", "prop", 1)),
    "yy": (("block.png", "block_item", 1), ("house.png", "prop", 1), ("map2.png", "terrain", 0), ("player.png", "reference_actor", 1), ("sky.png", "backdrop", 1), ("tree.png", "prop", 1), ("shot.xp", "shot_reference", 0)),
}


def _asset_output_name(world: str, filename: str) -> str:
    stem = Path(filename).stem.replace("_", "-")
    return f"legacy-{world}-{stem}"


ASSETS = tuple(
    LegacyAsset(world, filename, _asset_output_name(world, filename), kind, fmt)
    for world, files in STATIC_VERSION_FILES.items()
    for filename, kind, fmt in files
)

SPRITE_SPECS = (
    # xx/player.png: 9 animation columns x 8 view rows, no reflection row in
    # the prototype. The C++ XP loader treats angled sprites as projection +
    # reflection, so we duplicate the projection frames into the reflection
    # columns rather than fabricating a second visual owner.
    LegacySpriteSpec("xx", "player.png", "legacy-xx-player", 9, 8, 8, (9,), "rows_angles_duplicate_reflection", "reference_actor"),
    # yy/player.png: 18 columns x 8 view rows. Columns 0..8 are projection,
    # columns 9..17 are reflection, matching the C++ angled sprite layout.
    LegacySpriteSpec("yy", "player.png", "legacy-yy-player", 18, 8, 8, (9,), "rows_angles_projection_reflection", "reference_actor"),
    # FL-4137 / 2026-05-28 operator rule: definition 420's canonical sprite is
    # the step variant (assets/sprites/legacy-yy-block-step.xp, generated by
    # scripts/adhoc/2026-05-29-Generate-FL-4137-placed-block-step-XP-with-geometry-matched-.py).
    # The tall pipeline outputs `legacy-yy-block` and `legacy-yy-block-angles`
    # silently regenerated wrong-height variants that catalog flips kept
    # pointing at; both were dumpstered and these specs removed so the wrong
    # sprite cannot be reintroduced via a routine pipeline run. If a future
    # block variant is required, author it explicitly and route definition 420
    # only after operator confirmation that height fits kMpMaxImplicitStepUp.
    # Tree PNGs are composited by prototype JS, so these are static reference
    # XPs from the first authored column, not a full replacement for paint3d.
    LegacySpriteSpec("xx", "tree.png", "legacy-xx-tree", 12, 1, 0, (1,), "single_column_full_height", "prop_static_reference"),
    LegacySpriteSpec("yy", "tree.png", "legacy-yy-tree", 12, 2, 0, (1,), "single_column_full_height", "prop_static_reference"),
)

SLICE_SPECS = (
    # FL-4137: block slice spec removed for the same reason as the SPRITE_SPECS
    # above — would regenerate wrong-height block assets the catalog must not
    # point at. See operator rule + dumpster manifest.
    LegacySliceSpec("xx", "tree.png", "legacy-xx-tree", 12, 1, "tree_frame"),
    LegacySliceSpec("yy", "tree.png", "legacy-yy-tree", 12, 2, "tree_frame"),
)
SPECIALIZED_XP_OUTPUTS = {spec.output_name for spec in SPRITE_SPECS}


def _source_path(source_root: Path, asset: LegacyAsset) -> Path:
    return source_root / f"asciicker_{asset.world}_rip" / "images" / asset.filename


def _copied_source_path(image_out: Path, asset: LegacyAsset) -> Path:
    return image_out / asset.world / asset.filename


def _asset_url(base_url: str, asset: LegacyAsset) -> str:
    base = base_url.rstrip("/")
    if asset.filename.lower().endswith(".png"):
        return f"{base}/{asset.world}/images/{asset.filename}"
    return f"{base}/{asset.world}/{asset.filename}"


def _sha256(path: Path) -> str:
    digest = hashlib.sha256()
    with path.open("rb") as handle:
        for chunk in iter(lambda: handle.read(1024 * 1024), b""):
            digest.update(chunk)
    return digest.hexdigest()


def _encode_digit(value: int) -> int:
    if 0 <= value <= 9:
        return ord("0") + value
    if 10 <= value <= 35:
        return ord("A") + (value - 10)
    raise ValueError(f"metadata digit out of range: {value}")


def _empty_layer(width: int, height: int, bg=TRANSPARENT_KEY) -> XPLayer:
    layer = XPLayer(width, height)
    for y in range(height):
        for x in range(width):
            layer.data[y][x] = (0, bg, bg)
    return layer


def _metadata_layer(width: int, height: int, key: tuple[int, int, int],
                    angles: int, anim_lengths: tuple[int, ...]) -> XPLayer:
    layer = _empty_layer(width, height, key)
    layer.data[0][0] = (_encode_digit(angles), WHITE, key)
    for idx, length in enumerate(anim_lengths, start=1):
        if idx >= width:
            break
        layer.data[0][idx] = (_encode_digit(length), WHITE, key)
    return layer


def _countdown_layer(width: int, height: int, frame_height: int,
                     key: tuple[int, int, int]) -> XPLayer:
    layer = _empty_layer(width, height, key)
    for y in range(height):
        glyph = _encode_digit((frame_height - 1 - (y % frame_height)) % 36)
        for x in range(width):
            layer.data[y][x] = (glyph, WHITE, BLACK)
    return layer


def _dominant_color(image: Image.Image) -> tuple[int, int, int]:
    colors = image.getcolors(maxcolors=image.width * image.height)
    if not colors:
        return TRANSPARENT_KEY
    return max(colors, key=lambda item: item[0])[1]


def _image_has_color(image: Image.Image, rgb: tuple[int, int, int]) -> bool:
    colors = image.getcolors(maxcolors=image.width * image.height)
    return any(tuple(color) == rgb for _, color in colors or ())


def _keyed_rgb(rgb: tuple[int, int, int],
               source_key: tuple[int, int, int],
               xp_key: tuple[int, int, int]) -> tuple[int, int, int]:
    return xp_key if rgb == source_key else rgb


def _half_block_cells(frame: Image.Image,
                      source_key: tuple[int, int, int],
                      xp_key: tuple[int, int, int]) -> list[list[tuple[int, tuple[int, int, int], tuple[int, int, int]]]]:
    frame = frame.convert("RGB")
    height = (frame.height + 1) // 2
    rows = []
    for y in range(height):
        top_y = min(y * 2, frame.height - 1)
        bottom_y = min(y * 2 + 1, frame.height - 1)
        row = []
        for x in range(frame.width):
            top_rgb = _keyed_rgb(tuple(frame.getpixel((x, top_y))), source_key, xp_key)
            bottom_rgb = _keyed_rgb(tuple(frame.getpixel((x, bottom_y))), source_key, xp_key)
            row.append((220, bottom_rgb, top_rgb))
        rows.append(row)
    return rows


def _static_fmt1_cell(rgb: tuple[int, int, int]) -> tuple[int, tuple[int, int, int], tuple[int, int, int]]:
    # asciicker.com static prototypes pack cells as:
    #   R = depth/shade, G = CP437 glyph, B low nibble = fg index, B high nibble = bg index.
    # The C++ XP path has no depth byte, so depth remains source-only metadata in the PNG/manifest.
    glyph = rgb[1]
    fg_idx = rgb[2] & 0x0f
    bg_idx = (rgb[2] >> 4) & 0x0f
    fg = STATIC_FMT1_PALETTE[fg_idx]
    bg = STATIC_FMT1_PALETTE[bg_idx]
    return glyph, fg, bg


def _copy_static_fmt1_frame_to_layer(frame: Image.Image, layer: XPLayer,
                                     dst_x: int, dst_y: int) -> None:
    frame = frame.convert("RGB")
    for y in range(frame.height):
        for x in range(frame.width):
            layer.data[dst_y + y][dst_x + x] = _static_fmt1_cell(tuple(frame.getpixel((x, y))))


def _copy_frame_to_layer(frame: Image.Image, layer: XPLayer, dst_x: int, dst_y: int,
                         source_key: tuple[int, int, int],
                         xp_key: tuple[int, int, int]) -> None:
    rows = _half_block_cells(frame, source_key, xp_key)
    for y, row in enumerate(rows):
        for x, cell in enumerate(row):
            layer.data[dst_y + y][dst_x + x] = cell


def convert_sprite_grid_to_half_block_xp(source: Path, destination: Path,
                                         spec: LegacySpriteSpec) -> dict:
    image = Image.open(source).convert("RGB")
    if image.width % spec.frame_cols != 0 or image.height % spec.frame_rows != 0:
        raise ValueError(
            f"{source} is {image.width}x{image.height}, not divisible by "
            f"{spec.frame_cols}x{spec.frame_rows}"
        )
    frame_w = image.width // spec.frame_cols
    frame_h_px = image.height // spec.frame_rows
    frame_h = frame_h_px
    source_key = _dominant_color(image)
    key = TRANSPARENT_KEY

    anim_sum = sum(spec.anim_lengths)
    xp_cols = (2 * anim_sum) if spec.angles > 0 else anim_sum
    xp_w = frame_w * xp_cols
    xp_h = frame_h * max(1, spec.angles)
    visual = _empty_layer(xp_w, xp_h, key)

    def source_frame(col: int, row: int) -> Image.Image:
        x0 = col * frame_w
        y0 = row * frame_h_px
        return image.crop((x0, y0, x0 + frame_w, y0 + frame_h_px))

    if spec.layout == "rows_angles_projection_reflection":
        for angle in range(spec.angles):
            for col in range(xp_cols):
                _copy_static_fmt1_frame_to_layer(source_frame(col, angle), visual, col * frame_w, angle * frame_h)
    elif spec.layout == "rows_angles_duplicate_reflection":
        for angle in range(spec.angles):
            for col in range(anim_sum):
                frame = source_frame(col, angle)
                _copy_static_fmt1_frame_to_layer(frame, visual, col * frame_w, angle * frame_h)
                _copy_static_fmt1_frame_to_layer(frame, visual, (col + anim_sum) * frame_w, angle * frame_h)
    elif spec.layout == "columns_angles_rows_projection_reflection":
        for angle in range(spec.angles):
            _copy_static_fmt1_frame_to_layer(source_frame(angle, 0), visual, 0, angle * frame_h)
            _copy_static_fmt1_frame_to_layer(source_frame(angle, 1), visual, frame_w, angle * frame_h)
    elif spec.layout == "single_frame_first":
        _copy_static_fmt1_frame_to_layer(source_frame(0, 0), visual, 0, 0)
    elif spec.layout == "single_column_full_height":
        _copy_static_fmt1_frame_to_layer(source_frame(0, 0), visual, 0, 0)
    else:
        raise ValueError(f"unknown legacy sprite layout: {spec.layout}")

    xp = XPFile()
    xp.layers.append(_metadata_layer(xp_w, xp_h, key, spec.angles, spec.anim_lengths))
    xp.layers.append(_countdown_layer(xp_w, xp_h, frame_h, key))
    xp.layers.append(visual)
    destination.parent.mkdir(parents=True, exist_ok=True)
    xp.save(str(destination))

    return {
        "source_pixels": [image.width, image.height],
        "xp_cells": [xp_w, xp_h],
        "layers": len(xp.layers),
        "source_frame_pixels": [frame_w, frame_h_px],
        "xp_frame_cells": [frame_w, frame_h],
        "angles": spec.angles,
        "anim_lengths": list(spec.anim_lengths),
        "layout": f"static_fmt1_{spec.layout}",
        "source_transparent_key": list(source_key),
        "xp_transparent_key": list(key),
    }


def convert_png_to_half_block_xp(source: Path, destination: Path,
                                 keyed_transparency: bool) -> dict:
    image = Image.open(source).convert("RGB")
    frame_h = (image.height + 1) // 2
    key = TRANSPARENT_KEY
    source_key = TRANSPARENT_KEY if keyed_transparency and _image_has_color(image, TRANSPARENT_KEY) else (-1, -1, -1)
    visual = _empty_layer(image.width, frame_h, key)
    _copy_frame_to_layer(image, visual, 0, 0, source_key, key)

    xp = XPFile()
    xp.layers.append(_metadata_layer(image.width, frame_h, key, 0, (1,)))
    xp.layers.append(_countdown_layer(image.width, frame_h, frame_h, key))
    xp.layers.append(visual)
    destination.parent.mkdir(parents=True, exist_ok=True)
    xp.save(str(destination))

    return {
        "source_pixels": [image.width, image.height],
        "xp_cells": [image.width, frame_h],
        "layers": len(xp.layers),
        "source_frame_pixels": [image.width, image.height],
        "xp_frame_cells": [image.width, frame_h],
        "angles": 0,
        "anim_lengths": [1],
        "layout": "single_png_half_block_reference",
        "source_transparent_key": list(source_key) if source_key[0] >= 0 else None,
        "xp_transparent_key": list(key),
    }


def convert_static_fmt1_png_to_xp(source: Path, destination: Path) -> dict:
    image = Image.open(source).convert("RGB")
    key = TRANSPARENT_KEY
    visual = _empty_layer(image.width, image.height, key)
    _copy_static_fmt1_frame_to_layer(image, visual, 0, 0)

    xp = XPFile()
    xp.layers.append(_metadata_layer(image.width, image.height, key, 0, (1,)))
    xp.layers.append(_countdown_layer(image.width, image.height, image.height, key))
    xp.layers.append(visual)
    destination.parent.mkdir(parents=True, exist_ok=True)
    xp.save(str(destination))

    return {
        "source_pixels": [image.width, image.height],
        "xp_cells": [image.width, image.height],
        "layers": len(xp.layers),
        "source_frame_pixels": [image.width, image.height],
        "xp_frame_cells": [image.width, image.height],
        "angles": 0,
        "anim_lengths": [1],
        "layout": "static_fmt1_cell_encoded_reference",
        "source_transparent_key_index": STATIC_FMT1_KEY_INDEX,
        "xp_transparent_key": list(key),
    }


def export_source_slices(source: Path, slice_root: Path, spec: LegacySliceSpec) -> list[dict]:
    image = Image.open(source).convert("RGB")
    if image.width % spec.frame_cols != 0 or image.height % spec.frame_rows != 0:
        raise ValueError(
            f"{source} is {image.width}x{image.height}, not divisible by "
            f"{spec.frame_cols}x{spec.frame_rows}"
        )
    frame_w = image.width // spec.frame_cols
    frame_h = image.height // spec.frame_rows
    out_dir = slice_root / spec.output_name
    out_dir.mkdir(parents=True, exist_ok=True)
    rows = []
    for row in range(spec.frame_rows):
        for col in range(spec.frame_cols):
            path = out_dir / f"r{row:02d}_c{col:02d}.png"
            crop = image.crop((col * frame_w, row * frame_h, (col + 1) * frame_w, (row + 1) * frame_h))
            crop.save(path)
            rows.append(
                {
                    "world": spec.world,
                    "kind": spec.kind,
                    "source": str(source.relative_to(REPO_ROOT)),
                    "slice": str(path.relative_to(REPO_ROOT)),
                    "slice_sha256": _sha256(path),
                    "frame_col": col,
                    "frame_row": row,
                    "frame_pixels": [frame_w, frame_h],
                    "status": "source_slice",
                }
            )
    return rows


def download_static_assets(image_out: Path, base_url: str = STATIC_BASE_URL) -> list[dict]:
    rows = []
    for asset in ASSETS:
        destination = _copied_source_path(image_out, asset)
        destination.parent.mkdir(parents=True, exist_ok=True)
        url = _asset_url(base_url, asset)
        try:
            with urllib.request.urlopen(url) as response:
                destination.write_bytes(response.read())
        except urllib.error.HTTPError as exc:
            if asset.filename.lower().endswith(".xp"):
                rows.append(
                    {
                        "world": asset.world,
                        "kind": asset.kind,
                        "url": url,
                        "source": str(destination.relative_to(REPO_ROOT)),
                        "status": f"missing_source_http_{exc.code}",
                    }
                )
                continue
            raise FileNotFoundError(f"download failed for {url}: HTTP {exc.code}") from exc
        rows.append(
            {
                "world": asset.world,
                "kind": asset.kind,
                "url": url,
                "source": str(destination.relative_to(REPO_ROOT)),
                "source_sha256": _sha256(destination),
                "status": "downloaded_source",
            }
        )
    return rows


def import_assets(source_root: Path, image_out: Path, xp_out: Path,
                  download: bool = False) -> list[dict]:
    rows = []
    image_out.mkdir(parents=True, exist_ok=True)
    xp_out.mkdir(parents=True, exist_ok=True)
    if download:
        rows.extend(download_static_assets(image_out))
    for asset in ASSETS:
        copied_source = _copied_source_path(image_out, asset)
        source = copied_source if copied_source.exists() else _source_path(source_root, asset)
        if not source.exists():
            if download and asset.filename.lower().endswith(".xp"):
                continue
            raise FileNotFoundError(f"missing legacy source: {source}")
        copied_source.parent.mkdir(parents=True, exist_ok=True)
        if source != copied_source:
            shutil.copy2(source, copied_source)

        rows.append(
            {
                "world": asset.world,
                "kind": asset.kind,
                "source": str(copied_source.relative_to(REPO_ROOT)),
                "source_sha256": _sha256(copied_source),
                "status": "source_only",
            }
        )
        if copied_source.suffix.lower() == ".png" and asset.output_name not in SPECIALIZED_XP_OUTPUTS:
            xp_path = xp_out / f"{asset.output_name}.xp"
            if asset.fmt == 1:
                summary = convert_static_fmt1_png_to_xp(copied_source, xp_path)
                status = "xp_decoded_static_fmt1"
            else:
                keyed = asset.kind in {"prop", "reference_actor", "block_item", "prop_static_reference"}
                summary = convert_png_to_half_block_xp(copied_source, xp_path, keyed)
                status = "xp_reconstructed_reference"
            rows.append(
                {
                    "world": asset.world,
                    "kind": asset.kind,
                    "source": str(copied_source.relative_to(REPO_ROOT)),
                    "source_sha256": _sha256(copied_source),
                    "xp": str(xp_path.relative_to(REPO_ROOT)),
                    "xp_sha256": _sha256(xp_path),
                    "status": status,
                    **summary,
                }
            )
        elif copied_source.suffix.lower() == ".xp":
            xp_path = xp_out / f"{asset.output_name}.xp"
            shutil.copy2(copied_source, xp_path)
            rows.append(
                {
                    "world": asset.world,
                    "kind": asset.kind,
                    "source": str(copied_source.relative_to(REPO_ROOT)),
                    "source_sha256": _sha256(copied_source),
                    "xp": str(xp_path.relative_to(REPO_ROOT)),
                    "xp_sha256": _sha256(xp_path),
                    "status": "xp_source_copied",
                }
            )
    slice_root = image_out / DEFAULT_SLICE_DIRNAME
    for spec in SLICE_SPECS:
        source = image_out / spec.world / spec.filename
        if not source.exists():
            raise FileNotFoundError(f"missing copied legacy source: {source}")
        rows.extend(export_source_slices(source, slice_root, spec))
    for spec in SPRITE_SPECS:
        source = image_out / spec.world / spec.filename
        if not source.exists():
            raise FileNotFoundError(f"missing copied legacy source: {source}")
        xp_path = xp_out / f"{spec.output_name}.xp"
        summary = convert_sprite_grid_to_half_block_xp(source, xp_path, spec)
        rows.append(
            {
                "world": spec.world,
                "kind": spec.kind,
                "source": str(source.relative_to(REPO_ROOT)),
                "source_sha256": _sha256(source),
                "xp": str(xp_path.relative_to(REPO_ROOT)),
                "xp_sha256": _sha256(xp_path),
                "status": "xp_sliced",
                **summary,
            }
        )
    manifest_path = image_out / "manifest.json"
    manifest_path.write_text(json.dumps({"assets": rows}, indent=2) + "\n", encoding="utf-8")
    return rows


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--source-root", type=Path, default=DEFAULT_SOURCE_ROOT)
    parser.add_argument("--image-out", type=Path, default=DEFAULT_IMAGE_OUT)
    parser.add_argument("--xp-out", type=Path, default=DEFAULT_XP_OUT)
    parser.add_argument("--download-static", action="store_true",
                        help="download x3-x13/xx/yy loose static assets from asciicker.com before importing")
    parser.add_argument("--json", action="store_true")
    args = parser.parse_args()

    rows = import_assets(args.source_root, args.image_out, args.xp_out, args.download_static)
    if args.json:
        print(json.dumps({"imported": rows}, indent=2))
    else:
        for row in rows:
            if row["status"] == "xp_sliced":
                print(f"{row['source']} -> {row['xp']} {row['xp_cells'][0]}x{row['xp_cells'][1]}")
            else:
                print(f"{row['source']} source-only")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
