#pragma once

// Generated by scripts/dump_actor_visual_reachability.py.
// Server/deploy identity for the compiled actor visual table.

static constexpr const char* kServerActorVisualReachabilityScopeId = "server_reachability_scope:b18f0823d6b7f04b";
static constexpr const char* kServerActorVisualReachabilityHash = "c0dd1d0e142cc5dbb08d3a06368b9f97cfafe81046397524fbadbfd0cedceccd";
static constexpr const char* kServerActorVisualCatalogHash = "9aa4e65ab689d31c14dc3601be054a822c3b821b5b7f09b47eb469970f0b64be";
