"""Read/write the launcher's local `.asciicker.conf` settings."""

from __future__ import annotations

import os
import subprocess
from pathlib import Path

REPO_ROOT = Path(__file__).parent.parent.parent.resolve()
CONFIG_PATH = REPO_ROOT / ".asciicker.conf"

DEFAULTS = {
    "ASSET_DIR": str(REPO_ROOT / "assets"),
}

HIDDEN_FIELDS = {"BLOSM_API_KEY"}


def _git_info_exclude_path() -> Path | None:
    try:
        result = subprocess.run(
            ["git", "-C", str(REPO_ROOT), "rev-parse", "--git-dir"],
            capture_output=True,
            text=True,
            timeout=5,
            check=False,
        )
    except subprocess.TimeoutExpired:
        return None
    if result.returncode != 0 or not result.stdout.strip():
        return None
    git_dir = Path(result.stdout.strip())
    if not git_dir.is_absolute():
        git_dir = (REPO_ROOT / git_dir).resolve()
    return git_dir / "info" / "exclude"


def _ensure_git_ignored(path: Path) -> None:
    rel = str(path.relative_to(REPO_ROOT))
    check = subprocess.run(
        ["git", "-C", str(REPO_ROOT), "check-ignore", "-q", rel],
        capture_output=True,
        timeout=5,
        check=False,
    )
    if check.returncode == 0:
        return

    exclude_path = _git_info_exclude_path()
    if exclude_path is not None:
        exclude_path.parent.mkdir(parents=True, exist_ok=True)
        existing = ""
        try:
            if exclude_path.exists():
                existing = exclude_path.read_text()
            if rel not in {line.strip() for line in existing.splitlines()}:
                with exclude_path.open("a", encoding="utf-8") as handle:
                    if existing and not existing.endswith("\n"):
                        handle.write("\n")
                    handle.write(f"{rel}\n")
        except OSError:
            pass

        check = subprocess.run(
            ["git", "-C", str(REPO_ROOT), "check-ignore", "-q", rel],
            capture_output=True,
            timeout=5,
            check=False,
        )
        if check.returncode == 0:
            return

    raise RuntimeError(f"{rel} is not gitignored; refusing to write local settings.")


def load() -> dict[str, str]:
    values = dict(DEFAULTS)
    if not CONFIG_PATH.exists():
        return values

    try:
        raw = CONFIG_PATH.read_text()
    except OSError:
        return values

    for line in raw.splitlines():
        line = line.strip()
        if not line or line.startswith("#") or "=" not in line:
            continue
        key, _, value = line.partition("=")
        values[key.strip()] = value.strip()
    return values


def save(values: dict[str, str]) -> None:
    _ensure_git_ignored(CONFIG_PATH)

    tmp_path = CONFIG_PATH.with_name(".asciicker.conf.tmp")
    merged = dict(DEFAULTS)
    merged.update(values)

    lines = ["# .asciicker.conf - generated by the launcher, do not commit\n"]
    for key in sorted(merged):
        lines.append(f"{key}={merged[key]}\n")

    try:
        tmp_path.write_text("".join(lines))
        os.chmod(tmp_path, 0o600)
        tmp_path.replace(CONFIG_PATH)
        os.chmod(CONFIG_PATH, 0o600)
    except OSError:
        try:
            if tmp_path.exists():
                tmp_path.unlink()
        except OSError:
            pass
        raise


def validate_field(key: str, value: str) -> str | None:
    if "\n" in value or "\x00" in value:
        return "value contains invalid control characters"

    if key == "ASSET_DIR":
        path = Path(value).expanduser().resolve()
        if not path.exists():
            return f"path not found: {path}"
        if not path.is_dir():
            return f"not a directory: {path}"
        return None

    if key == "BLOSM_API_KEY":
        if not value.strip():
            return "API key cannot be blank"
        return None

    return None
