#!/usr/bin/env python3
"""Emit exact ActorVisualProfile keys from the server-owned C++ catalog."""

from __future__ import annotations

import argparse
import hashlib
import json
import subprocess
import sys
import tempfile
from pathlib import Path


REPO_ROOT = Path(__file__).resolve().parents[1]
CPP_SOURCE = REPO_ROOT / "server/actor_visual_reachability_dump.cpp"
SERVER_CATALOG_SOURCE = REPO_ROOT / "server/actor_visual_catalog_source.h"
DEFAULT_OUT = REPO_ROOT / "assets/actor_visual_profiles/current/server_reachable_keys.json"
DEFAULT_IDENTITY_HEADER_OUT = (
    REPO_ROOT / "server/actor_visual_reachability_identity.generated.h"
)


def _canonical_hash(value: object) -> str:
    encoded = json.dumps(value, sort_keys=True, separators=(",", ":")) + "\n"
    return hashlib.sha256(encoded.encode("utf-8")).hexdigest()


def _build_and_run() -> dict:
    with tempfile.TemporaryDirectory(prefix="actor-visual-reachability-") as tmp:
        executable = Path(tmp) / "actor_visual_reachability_dump"
        subprocess.run(
            [
                "c++",
                "-std=c++17",
                "-I.",
                "-Iserver",
                str(CPP_SOURCE.relative_to(REPO_ROOT)),
                "-o",
                str(executable),
            ],
            cwd=REPO_ROOT,
            check=True,
            stdout=subprocess.PIPE,
            stderr=subprocess.PIPE,
            text=True,
        )
        run = subprocess.run(
            [str(executable)],
            cwd=REPO_ROOT,
            check=True,
            stdout=subprocess.PIPE,
            stderr=subprocess.PIPE,
            text=True,
        )
    doc = json.loads(run.stdout)
    if doc.get("source") != "server/actor_visual_reachability_dump.cpp":
        raise ValueError(f"unexpected reachability source: {doc.get('source')!r}")
    if doc.get("catalog_source") != "server/actor_visual_catalog_source.h":
        raise ValueError(f"unexpected catalog source: {doc.get('catalog_source')!r}")
    if doc.get("server_markers_ok") is not True:
        raise ValueError(f"server reachability failed: {doc.get('errors')!r}")
    keys = doc.get("reachable_keys")
    if not isinstance(keys, list) or len(keys) != doc.get("reachable_key_count"):
        raise ValueError("server reachability count does not match emitted keys")
    profiles = doc.get("catalog_profiles")
    if (
        not isinstance(profiles, list)
        or len(profiles) != doc.get("catalog_profile_count")
        or not profiles
    ):
        raise ValueError("server catalog profile count does not match emitted profiles")
    scope_seed = {
        "schema_id": doc.get("schema_id"),
        "source": doc.get("source"),
        "catalog_source": doc.get("catalog_source"),
    }
    doc["server_reachability_scope_id"] = (
        "server_reachability_scope:" + _canonical_hash(scope_seed)[:16]
    )
    doc["server_reachability_hash"] = _canonical_hash(
        {
            "schema_id": doc.get("schema_id"),
            "source": doc.get("source"),
            "catalog_source": doc.get("catalog_source"),
            "catalog_profiles": profiles,
            "reachable_keys": keys,
        }
    )
    doc["server_catalog_hash"] = hashlib.sha256(
        SERVER_CATALOG_SOURCE.read_bytes()
    ).hexdigest()
    return doc


def _json_text(doc: dict) -> str:
    return json.dumps(doc, indent=2, sort_keys=True) + "\n"


def _identity_header(doc: dict) -> str:
    return "\n".join(
        [
            "#pragma once",
            "",
            "// Generated by scripts/dump_actor_visual_reachability.py.",
            "// Server/deploy identity for the compiled actor visual table.",
            "",
            "static constexpr const char* kServerActorVisualReachabilityScopeId = "
            + json.dumps(doc["server_reachability_scope_id"])
            + ";",
            "static constexpr const char* kServerActorVisualReachabilityHash = "
            + json.dumps(doc["server_reachability_hash"])
            + ";",
            "static constexpr const char* kServerActorVisualCatalogHash = "
            + json.dumps(doc["server_catalog_hash"])
            + ";",
            "",
        ]
    )


def _resolve(path: Path) -> Path:
    return path if path.is_absolute() else REPO_ROOT / path


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument("--out", type=Path, default=DEFAULT_OUT)
    parser.add_argument(
        "--identity-header-out", type=Path, default=DEFAULT_IDENTITY_HEADER_OUT
    )
    parser.add_argument("--check", action="store_true")
    args = parser.parse_args(argv)
    try:
        doc = _build_and_run()
    except (OSError, subprocess.CalledProcessError, ValueError, json.JSONDecodeError) as exc:
        print(f"FAIL - server reachability C++ dump failed: {exc}")
        return 1
    out_path = _resolve(args.out)
    identity_path = _resolve(args.identity_header_out)
    expected = {
        out_path: _json_text(doc),
        identity_path: _identity_header(doc),
    }
    if args.check:
        for path, text in expected.items():
            try:
                current = path.read_text(encoding="utf-8")
            except OSError:
                print(f"FAIL - reachability artifact missing: {path.relative_to(REPO_ROOT)}")
                return 1
            if current != text:
                print(f"FAIL - reachability artifact stale: {path.relative_to(REPO_ROOT)}")
                return 1
        print("PASS - server reachability artifact is current")
        return 0
    for path, text in expected.items():
        path.parent.mkdir(parents=True, exist_ok=True)
        path.write_text(text, encoding="utf-8")
        print(f"Wrote {path.relative_to(REPO_ROOT)}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
